theme = "nord-dark"
icons = "awesome"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used} {mem_used_percents}"
format_swap = "{swap_used}/{swap_total}({swap_used_percents})"
icons =true
clickable = true
interval = 5
warning_mem = 80

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]

[[block]]
block = "sound"
format = "{volume}"
step_width = 5
on_click = "pactl set-sink-mute 0 toggle"

[[block]]
block = "cpu"
interval = 1
format = "{utilization} {frequency}"

[[block]]
block = "net"
format = "{ssid}"
interval = 5

[[block]]
block = "time"
interval = 5
format = "%m/%d(%a) %R"

